//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RGR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int id { get; set; }
        public string Name_Rus { get; set; }
        public string Name_Latin { get; set; }
        public string Name_Eng { get; set; }
        public byte[] photo { get; set; }
    }
}
